kind: Deployment
apiVersion: apps/v1
metadata:
  name: flash-main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-main
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flash-main
    spec:
      containers:
        - name: flash-main
          image: rexben/flash-main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: flash-main
  labels:
    app: flash-main
spec:
  type: LoadBalancer
  selector:
    app: flash-main
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

## local dev

# kind: Service
# apiVersion: v1
# metadata:
#   name: flash-main
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       nodePort: 31000
#   selector:
#     app: flash-main