kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: rexben/react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: react-app
#   labels:
#     app: react-app
# spec:
#   type: LoadBalancer
#   selector:
#     app: react-app
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP

kind: Service
apiVersion: v1
metadata:
  name: react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-app