version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  lint:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install dependencies and Lint app
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv virtualenv
            . virtualenv/bin/activate
            make install
            make lint
  
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build and push docker image to dockerhub
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker build -t rexben/flash-main:${CIRCLE_WORKFLOW_ID:0:7} .
            docker push rexben/flash-main

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          flash-main
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
            kubectl get nodes
            kubectl get deployment
            echo parameters.cluster-name
          name: Test cluster

  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          flash-main
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: depl.yml
          resource-name: deployment/flash-main


workflows:
  deployment:
    jobs:
      # - lint
      # - build:
      #     requires:
      #       - lint
      # - aws-eks/create-cluster:
      #     cluster-name: flash-main
      # - create-deployment:
      #     cluster-name: flash-main
      #     requires:
      #       - aws-eks/create-cluster
      # - aws-eks/update-container-image:
      #     cluster-name: flash-main
      #     container-image-updates: 'flash-main=rexben/flash-main'
      #     post-steps:
      #       - kubernetes/delete-resource:
      #           resource-names: flash-main
      #           resource-types: deployment
      #           wait: true
      #     record: true
      #     requires:
      #       - create-deployment
      #     resource-name: deployment/flash-main
      # - test-cluster:
      #     cluster-name: flash-main
      #     requires:
      #       - aws-eks/update-container-image
      - aws-eks/delete-cluster:
          cluster-name: flash-app
          # requires:
          #   - test-cluster
